name: nga_sdk
description: 'SDK for C++, Dart (Flutter), Go, Shell, etc.'
version: 4.4.6
repository: https://github.com/NGA-SDK/NGA-SDK.dart
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  system_theme: ^3.1.2
  vector_graphics: ^1.1.19
  window_manager: ^0.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
flutter:
  fonts:
    - family: BOOT
      fonts:
        - asset: nga_dat/boot.ttf
  assets:
    - nga_dat/arrow_forward.vec